export const paths = {
  home: '/',
  shop: '/shop',
  productDetails: (id) => `/shop/${id}`,
  collection: (id) => `/collections/${id}`,
  auctions: '/auctions',
  auctionDetails: (id) => `/auctions/${id}`,
  offers: '/offers',
  favorites: '/favorites',
  cart: '/cart',
  checkout: '/checkout',
  checkoutSuccess: (orderId) => `/checkout/success/${orderId}`,
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  account: '/account',
  accountOrders: '/account/orders',
  accountOrderDetails: (id) => `/account/orders/${id}`,
  accountBids: '/account/bids',
  about: '/about',
  contact: '/contact',
  faq: '/faq',
};
